# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: SecurityManagerRepo
    type: github
    endpoint: MyGitHubServiceConnection
    name: MyGitHubOrgOrUser/MyGitHubRepo
    ref: features/tools

stages:
- template: build-rm-parent.yml

- template: ace.yml
  parameters:
    env: NV-INT

- stage: intTests
  jobs:
  - job: runAllTestsInParallel
    strategy:
      matrix:
        SMTests:
          repo: SecurityMangerTests
        OSTests:
          name: ObjectServiceTests
        NSTests:
          name: NotificationServiceTests
      maxParallel: 5
    steps:
      # Run the steps. 
      - checkout: $( gitUrl )
      - script: echo "Running $( name ) " && sleep 10

- template: ace.yml
  parameters:
    env: NV-FQA1

# Kick off regressions maybe?

- template: ace.yml
  parameters:
    env: UAT
